image: php:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: import_employees
  MYSQL_ROOT_PASSWORD: import@employees

cache:
  paths:
  - vendor/

before_script:
  # Update packages 
  - apt-get update -yqq
  
  # Install dependencies
  - apt-get install git libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq

  # Install php extensions
  - docker-php-ext-install mbstring mcrypt pdo_mysql curl json intl gd xml zip bz2 opcache

  # Install Composer and project dependencies.
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install 

  - cp .env.testing .env

  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan config:cache

test:
  script:
  # run laravel tests
  - php vendor/bin/phpunit --colors=never 
